---
- name: Install the appropriate .deb package based on OS version
  hosts: all
  gather_facts: yes
  become: yes  # Escalate privileges to superuser
  tasks:
    - name: Install the .deb package for Debian 11
      apt:
        deb: /home/ansible/VC/anton/VC/vc_deb11.deb
      when: ansible_distribution == "Debian" and ansible_distribution_version == "11"

    - name: Install the .deb package for Debian 10
      apt:
        deb: /home/ansible/VC/anton/VC/vc_deb10.deb
      when: ansible_distribution == "Debian" and ansible_distribution_version == "10"

    - name: Install the .deb package for Debian 9
      apt:
        deb: /home/ansible/VC/anton/VC/vc_deb9.deb
      when: ansible_distribution == "Debian" and ansible_distribution_version == "9"

    - name: Install the .deb package for Ubuntu 16.04
      apt:
        deb: /home/ansible/VC/anton/VC/vc_ubuntu16.deb
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

    - name: Install the .deb package for Ubuntu 18.04
      apt:
        deb: /home/ansible/VC/anton/VC/vc_ubuntu18.deb
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

    - name: Install the .deb package for Ubuntu 22.04
      apt:
        deb: /home/ansible/VC/anton/VC/vc_ubuntu22.deb
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
