- hosts: all
  become: yes
  tasks:
    - name: Copy the shell script to the remote host
      ansible.builtin.copy:
        src: nodeinstall.sh
        dest: /root/nodeinstall.sh
        owner: root
        group: root
        mode: '0755'

    - name: Execute the shell script on the remote host
      ansible.builtin.shell: /root/nodeinstall.sh
      args:
        executable: /bin/bash

    - name: Reload systemd daemon
      ansible.builtin.shell: sudo systemctl daemon-reload

    - name: Start node_exporter service
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: yes

    - name: Enable node_exporter service
      ansible.builtin.service:
        name: node_exporter
        enabled: yes

    - name: Check node_exporter service status
      ansible.builtin.systemd:
        name: node_exporter
        state: started
