apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app : my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: ant2
  template:
    metadata:
      labels:
        project: ant2   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : ant2-web
          image: kentik13/k8sphp:version2
          ports:
            - containerPort: 80
