#simple compose nginx
version: "3"
services:
  website:
    image: nginx
    ports:
      - "1234:80"
    restart: always
  website2:
    image: nginx
    ports:
      - "3333:80"
    restart: always
    networks:
      antony:
        ipv4_address: "192.168.92.21"
networks:
  antony:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
