version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
#   depends_on:
#      - mysql
    environment: 
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "password"  
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:5.7"
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  oyeah:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"
